## static_territories
UPDATE static_territories SET tr_name_de='Afrika' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_de='Ozeanien' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_de='Nord-, Mittel- und Südamerika' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_de='Asien' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_de='Europa' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_de='Ostasien' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_de='Südostasien' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_de='0' WHERE tr_iso_nr='143';
UPDATE static_territories SET tr_name_de='Westasien' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_de='Südeuropa' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_de='Osteuropa' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_de='Nordeuropa' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_de='Westeuropa' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_de='Südamerika' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_de='Mittelamerika' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_de='Nordamerika' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_de='Karibik' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_de='Westafrika' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_de='Ostafrika' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_de='Nordafrika' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_de='Zentralafrika' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_de='Südafrika' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_de='Australien und Neuseeland' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_de='Melanesien' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_de='Mikronesien' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_de='Polynesien' WHERE tr_iso_nr='61';
UPDATE static_territories SET tr_name_de='0' WHERE tr_iso_nr='34';


## static_countries
UPDATE static_countries SET cn_short_de='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_de='Vereinigte Arabische Emirate' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_de='Afghanistan' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_de='Antigua und Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_de='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_de='Albanien' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_de='Armenien' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_de='Niederländische Antillen' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_de='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_de='Antarktis' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_de='Argentinien' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_de='Amerikanisch-Samoa' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_de='Österreich' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_de='Australien' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_de='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_de='Aserbaidschan' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_de='Bosnien und Herzegowina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_de='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_de='Bangladesch' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_de='Belgien' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_de='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_de='Bulgarien' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_de='Bahrain' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_de='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_de='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_de='Bermuda' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_de='Brunei Darussalam' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_de='Bolivien' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_de='Brasilien' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_de='Bahamas' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_de='Bhutan' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_de='Bouvetinsel' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_de='Botsuana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_de='Weißrussland' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_de='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_de='Kanada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_de='Kokosinseln (Keeling)' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_de='Demokratische Republik Kongo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_de='Zentralafrikanische Republik' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_de='Kongo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_de='Schweiz' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_de='Elfenbeinküste' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_de='Cookinseln' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_de='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_de='Kamerun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_de='China' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_de='Kolumbien' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_de='Costa Rica' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_de='Kuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_de='Kap Verde' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_de='Weihnachtsinsel' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_de='Zypern' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_de='Tschechische Republik' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_de='Deutschland' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_de='Dschibuti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_de='Dänemark' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_de='Dominica' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_de='Dominikanische Republik' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_de='Algerien' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_de='Ecuador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_de='Estland' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_de='Ägypten' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_de='Westsahara' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_de='Eritrea' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_de='Spanien' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_de='Äthiopien' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_de='Finnland' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_de='Fidschi' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_de='Falklandinseln' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_de='Mikronesien' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_de='Färöer' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_de='Frankreich' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_de='Gabun' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_de='Großbritannien' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_de='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_de='Georgien' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_de='Französisch-Guayana' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_de='Ghana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_de='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_de='Grönland' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_de='Gambia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_de='Guinea' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_de='Guadeloupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_de='Äquatorialguinea' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_de='Griechenland' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_de='Südgeorgien und die Südlichen Sandwichinseln' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_de='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_de='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_de='Guinea-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_de='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_de='Hong Kong S.A.R., China' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_de='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_de='Kroatien' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_de='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_de='Ungarn' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_de='Indonesien' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_de='Irland' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_de='Israel' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_de='Indien' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_de='Britisches Territorium im Indischen Ozean' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_de='Irak' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_de='Iran' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_de='Island' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_de='Italien' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_de='Jamaika' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_de='Jordanien' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_de='Japan' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_de='Kenia' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_de='Kirgisistan' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_de='Kambodscha' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_de='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_de='Komoren' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_de='St. Kitts und Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_de='Demokratische Volksrepublik Korea' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_de='Republik Korea' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_de='Kuwait' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_de='Kaimaninseln' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_de='Kasachstan' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_de='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_de='Libanon' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_de='St. Lucia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_de='Liechtenstein' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_de='Sri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_de='Liberia' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_de='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_de='Litauen' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_de='Luxemburg' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_de='Lettland' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_de='Libyen' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_de='Marokko' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_de='Monaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_de='Republik Moldau' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_de='Madagaskar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_de='Marschallinseln' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_de='Mazedonien' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_de='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_de='Myanmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_de='Mongolei' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_de='Macau S.A.R., China' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_de='Nördliche Marianen' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_de='Martinique' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_de='Mauretanien' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_de='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_de='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_de='Mauritius' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_de='Malediven' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_de='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_de='Mexiko' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_de='Malaysia' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_de='Mosambik' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_de='Namibia' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_de='Neukaledonien' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_de='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_de='Norfolkinsel' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_de='Nigeria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_de='Nicaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_de='Niederlande' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_de='Norwegen' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_de='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_de='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_de='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_de='Neuseeland' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_de='Oman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_de='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_de='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_de='Französisch-Polynesien' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_de='Papua-Neuguinea' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_de='Philippinen' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_de='Pakistan' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_de='Polen' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_de='St. Pierre und Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_de='Pitcairn' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_de='Puerto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_de='Portugal' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_de='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_de='Paraguay' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_de='Katar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_de='Reunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_de='Rumänien' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_de='Russische Föderation' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_de='Ruanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_de='Saudi-Arabien' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_de='Salomonen' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_de='Seychellen' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_de='Sudan' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_de='Schweden' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_de='Singapur' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_de='St. Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_de='Slowenien' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_de='Svalbard und Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_de='Slowakei' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_de='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_de='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_de='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_de='Somalien' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_de='Suriname' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_de='São Tomé und Príncipe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_de='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_de='Syrien' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_de='Swasiland' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_de='Turks- und Caicosinseln' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_de='Tschad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_de='Französische Süd- und Antarktisgebiete' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_de='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_de='Thailand' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_de='Tadschikistan' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_de='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_de='Turkmenistan' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_de='Tunesien' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_de='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_de='Osttimor' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_de='Türkei' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_de='Trinidad und Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_de='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_de='Taiwan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_de='Tansania' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_de='Ukraine' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_de='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_de='Amerikanisch-Ozeanien' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_de='Vereinigte Staaten von Amerika' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_de='Uruguay' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_de='Usbekistan' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_de='Vatikanstaat' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_de='St. Vinzent und die Grenadinen' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_de='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_de='Britische Jungferninseln' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_de='Amerikanische Jungferninseln' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_de='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_de='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_de='Wallis und Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_de='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_de='Jemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_de='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_de='Südafrika' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_de='Sambia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_de='Simbabwe' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_de='Palästinensische Gebiete' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_de='Serbien und Montenegro' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_de='Alandinseln' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_de='Heard und McDonaldinseln' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_de='Montenegro' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_de='Serbien' WHERE cn_iso_2='RS';


## static_country_zones
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='AK';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='AZ';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_de='Kalifornien' WHERE zn_country_iso_2='US' AND zn_code='CA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='CO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='CT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='DE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='DC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='FL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='GA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='GU';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='HI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='ID';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='IL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='IN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='IA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='KS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='KY';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='LA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='ME';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='MD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='MA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='MI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='MN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='MO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='NE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='NV';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='NH';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='NJ';
UPDATE static_country_zones SET zn_name_de='Neu Mexiko' WHERE zn_country_iso_2='US' AND zn_code='NM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='NY';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='NC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='ND';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='OH';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='OK';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='OR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='RI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='SC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='SD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='TN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='TX';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='UT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='VT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='VA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='WA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='WV';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='WI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='US' AND zn_code='WY';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CA' AND zn_code='AB';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CA' AND zn_code='BC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CA' AND zn_code='MB';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CA' AND zn_code='NF';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CA' AND zn_code='NB';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CA' AND zn_code='NS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CA' AND zn_code='NT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CA' AND zn_code='NU';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CA' AND zn_code='ON';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CA' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CA' AND zn_code='QC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CA' AND zn_code='SK';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CA' AND zn_code='YT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='NDS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='BAW';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='BAY';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='BER';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='BRG';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='BRE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='HAM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='HES';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='MEC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='NRW';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='RHE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='SAR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='SAS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='SAC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='SCN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='DE' AND zn_code='THE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AT' AND zn_code='WI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AT' AND zn_code='NO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AT' AND zn_code='OO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AT' AND zn_code='SB';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AT' AND zn_code='KN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AT' AND zn_code='ST';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AT' AND zn_code='TI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AT' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AT' AND zn_code='VB';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='AG';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='AI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='BE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='BS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='FR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='GE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='GL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='GR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='JU';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='LU';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='NE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='NW';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='OW';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='SG';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='SH';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='SO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='SZ';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='TG';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='TI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='UR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='VD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='VS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='ZG';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='CH' AND zn_code='ZH';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Alava';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Malaga';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Segovia';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Granada';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Jaen';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Sevilla';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Barcelona';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Valencia';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Alicante';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Almeria';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Asturias';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Avila';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Badajoz';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Burgos';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Caceres';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Cadiz';
UPDATE static_country_zones SET zn_name_de='Kantabrien' WHERE zn_country_iso_2='ES' AND zn_code='Cantabria';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Castellon';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Ceuta';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Ciudad Real';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Cordoba';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Cuenca';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Girona';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Las Palmas';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Guadalajara';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Guipuzcoa';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Huelva';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Huesca';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='A Coruña';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='La Rioja';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Leon';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Lugo';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Lleida';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Madrid';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Baleares';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Murcia';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Navarra';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Ourense';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Palencia';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Pontevedra';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Salamanca';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Soria';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Tarragona';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Tenerife';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Teruel';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Toledo';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Valladolid';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Vizcaya';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Zamora';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Zaragoza';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='ES' AND zn_code='Melilla';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='AGS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='BCS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='BC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='CAM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='CHIS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='CHIH';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='COAH';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='COL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='DIF';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='DGO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='GTO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='GRO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='HGO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='JAL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='MEX';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='MICH';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='MOR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='NAY';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='NL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='OAX';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='PUE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='QRO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='QROO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='SLP';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='SIN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='SON';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='TAB';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='TAMPS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='TLAX';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='VER';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='YUC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='MX' AND zn_code='ZAC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AU' AND zn_code='ACT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AU' AND zn_code='NSW';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AU' AND zn_code='NT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AU' AND zn_code='QLD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AU' AND zn_code='SA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AU' AND zn_code='TAS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AU' AND zn_code='VIC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='AU' AND zn_code='WA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='AG';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='AN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='AO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='AP';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='AQ';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='AT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='AV';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='BA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='BG';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='BI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='BN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='BO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='BR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='BS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='BZ';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='CA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='CB';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='CE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='CH';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='CL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='CN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='CO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='CR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='CS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='CT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='CZ';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='EN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='FE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='FG';
UPDATE static_country_zones SET zn_name_de='Florenz' WHERE zn_country_iso_2='IT' AND zn_code='FI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='FO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='FR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='GE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='GO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='GR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='IM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='IS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='KR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='LC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='LE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='LI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='LO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='LT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='LU';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='MC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='ME';
UPDATE static_country_zones SET zn_name_de='Mailand' WHERE zn_country_iso_2='IT' AND zn_code='MI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='MN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='MO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='NA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='NO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='NU';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='OR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='PC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='PD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='PG';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='PI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='PN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='PS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='PT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='PV';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='PO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='PZ';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='RA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='RC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='RE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='RG';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='RI';
UPDATE static_country_zones SET zn_name_de='Rom' WHERE zn_country_iso_2='IT' AND zn_code='RM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='RN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='RO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='SA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='SI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='SO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='SP';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='SR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='SS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='SV';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='TA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='TE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='TN';
UPDATE static_country_zones SET zn_name_de='Turin' WHERE zn_country_iso_2='IT' AND zn_code='TO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='TP';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='TR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='TS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='TV';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='UD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='VA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='VC';
UPDATE static_country_zones SET zn_name_de='Venedig' WHERE zn_country_iso_2='IT' AND zn_code='VE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='VI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='VP';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='VR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='VT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IT' AND zn_code='VV';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='ALD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='ARM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='ATM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='BDS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='BFD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='BIR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='BLG';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='BRI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='BRK';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='BRS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='BUX';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='CAP';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='CAR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='CAS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='CBA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='CBE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='CER';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='CHI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='CHS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='CLD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='CNL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='CON';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='CTR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='CVE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='DEN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='DFD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='DGL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='DHM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='DOR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='DVN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='DWN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='DYS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='ESX';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='FER';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='FFE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='FLI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='FMH';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='GDD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='GLO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='GLR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='GNM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='GNS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='GNW';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='GRN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='GUR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='GWT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='HBS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='HFD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='HLD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='HPH';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='HWR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='IOM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='IOW';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='ISL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='JER';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='KNT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='LCN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='LDN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='LDR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='LEC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='LNH';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='LON';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='LTE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='LTM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='LTW';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='MCH';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='MER';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='MON';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='MSY';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='NET';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='NEW';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='NHM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='NLD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='NOR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='NOT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='NWH';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='OFE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='ORK';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='PEM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='PWS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='SCD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='SFD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='SFK';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='SLD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='SOM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='SPE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='SRK';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='SRY';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='SWA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='SXE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='SXW';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='TAF';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='TOR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='TWR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='TYR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='TYS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='VAL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='WIL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='WKS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='WLT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='WMD';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='WRE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='YSN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='YSS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='GB' AND zn_code='YSW';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='CAR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='CAV';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='CLA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='COR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='DON';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='DUB';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='GAL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='KER';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='KIL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='KLK';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='LAO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='LEI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='LIM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='LON';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='LOU';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='MAY';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='MEA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='MON';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='OFF';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='ROS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='SLI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='TIP';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='WAT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='WES';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='WEX';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='IE' AND zn_code='WIC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='AC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='AP';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='AM';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='BA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='CE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='DF';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='ES';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='GO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='MA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='MG';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='PB';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='PI';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='RJ';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='RN';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='RO';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='RR';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='RS';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='SC';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='SE';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='SP';
UPDATE static_country_zones SET zn_name_de='' WHERE zn_country_iso_2='BR' AND zn_code='TO';


## static_currencies
UPDATE static_currencies SET cu_name_de='UAE Dirham',cu_sub_name_de='' WHERE cu_iso_3='AED';
UPDATE static_currencies SET cu_name_de='Lek',cu_sub_name_de='' WHERE cu_iso_3='ALL';
UPDATE static_currencies SET cu_name_de='Dram',cu_sub_name_de='' WHERE cu_iso_3='AMD';
UPDATE static_currencies SET cu_name_de='Niederl. Antillen Gulden',cu_sub_name_de='' WHERE cu_iso_3='ANG';
UPDATE static_currencies SET cu_name_de='Kwanza',cu_sub_name_de='' WHERE cu_iso_3='AOA';
UPDATE static_currencies SET cu_name_de='Argentinischer Peso',cu_sub_name_de='' WHERE cu_iso_3='ARS';
UPDATE static_currencies SET cu_name_de='Australischer Dollar',cu_sub_name_de='' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_de='Aruba Florin',cu_sub_name_de='' WHERE cu_iso_3='AWG';
UPDATE static_currencies SET cu_name_de='',cu_sub_name_de='' WHERE cu_iso_3='AZN';
UPDATE static_currencies SET cu_name_de='Konvertierbare Mark',cu_sub_name_de='' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_de='Barbados-Dollar',cu_sub_name_de='' WHERE cu_iso_3='BBD';
UPDATE static_currencies SET cu_name_de='Taka',cu_sub_name_de='' WHERE cu_iso_3='BDT';
UPDATE static_currencies SET cu_name_de='Lew',cu_sub_name_de='' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_de='Bahrain-Dinar',cu_sub_name_de='' WHERE cu_iso_3='BHD';
UPDATE static_currencies SET cu_name_de='Burundi-Franc',cu_sub_name_de='' WHERE cu_iso_3='BIF';
UPDATE static_currencies SET cu_name_de='Bermuda-Dollar',cu_sub_name_de='' WHERE cu_iso_3='BMD';
UPDATE static_currencies SET cu_name_de='Brunei-Dollar',cu_sub_name_de='' WHERE cu_iso_3='BND';
UPDATE static_currencies SET cu_name_de='Boliviano',cu_sub_name_de='' WHERE cu_iso_3='BOB';
UPDATE static_currencies SET cu_name_de='Real',cu_sub_name_de='' WHERE cu_iso_3='BRL';
UPDATE static_currencies SET cu_name_de='Bahama-Dollar',cu_sub_name_de='' WHERE cu_iso_3='BSD';
UPDATE static_currencies SET cu_name_de='Ngultrum',cu_sub_name_de='' WHERE cu_iso_3='BTN';
UPDATE static_currencies SET cu_name_de='Pula',cu_sub_name_de='' WHERE cu_iso_3='BWP';
UPDATE static_currencies SET cu_name_de='Belarus Rubel (neu)',cu_sub_name_de='' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_de='Belize-Dollar',cu_sub_name_de='' WHERE cu_iso_3='BZD';
UPDATE static_currencies SET cu_name_de='Kanadischer Dollar',cu_sub_name_de='' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_de='Franc congolais',cu_sub_name_de='' WHERE cu_iso_3='CDF';
UPDATE static_currencies SET cu_name_de='Schweizer Franken',cu_sub_name_de='' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_de='Chilenischer Peso',cu_sub_name_de='' WHERE cu_iso_3='CLP';
UPDATE static_currencies SET cu_name_de='Renminbi Yuan',cu_sub_name_de='' WHERE cu_iso_3='CNY';
UPDATE static_currencies SET cu_name_de='Kolumbianischer Peso',cu_sub_name_de='' WHERE cu_iso_3='COP';
UPDATE static_currencies SET cu_name_de='Costa Rica Colon',cu_sub_name_de='' WHERE cu_iso_3='CRC';
UPDATE static_currencies SET cu_name_de='Kubanischer Peso',cu_sub_name_de='' WHERE cu_iso_3='CUP';
UPDATE static_currencies SET cu_name_de='Kap Verde Escudo',cu_sub_name_de='' WHERE cu_iso_3='CVE';
UPDATE static_currencies SET cu_name_de='Zypern Pfund',cu_sub_name_de='' WHERE cu_iso_3='CYP';
UPDATE static_currencies SET cu_name_de='Tschechische Krone',cu_sub_name_de='' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_de='Dschibuti-Franc',cu_sub_name_de='' WHERE cu_iso_3='DJF';
UPDATE static_currencies SET cu_name_de='Dänische Krone',cu_sub_name_de='' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_de='Dominikanischer Peso',cu_sub_name_de='' WHERE cu_iso_3='DOP';
UPDATE static_currencies SET cu_name_de='Algerischer Dinar',cu_sub_name_de='' WHERE cu_iso_3='DZD';
UPDATE static_currencies SET cu_name_de='Estnische Krone',cu_sub_name_de='' WHERE cu_iso_3='EEK';
UPDATE static_currencies SET cu_name_de='Ägyptisches Pfund',cu_sub_name_de='' WHERE cu_iso_3='EGP';
UPDATE static_currencies SET cu_name_de='Nakfa',cu_sub_name_de='' WHERE cu_iso_3='ERN';
UPDATE static_currencies SET cu_name_de='Birr',cu_sub_name_de='' WHERE cu_iso_3='ETB';
UPDATE static_currencies SET cu_name_de='Euro',cu_sub_name_de='' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_de='Fidschi Dollar',cu_sub_name_de='' WHERE cu_iso_3='FJD';
UPDATE static_currencies SET cu_name_de='Falkland Pfund',cu_sub_name_de='' WHERE cu_iso_3='FKP';
UPDATE static_currencies SET cu_name_de='Pfund Sterling',cu_sub_name_de='' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_de='Georgischer Lari',cu_sub_name_de='' WHERE cu_iso_3='GEL';
UPDATE static_currencies SET cu_name_de='Cedi',cu_sub_name_de='' WHERE cu_iso_3='GHC';
UPDATE static_currencies SET cu_name_de='Gibraltar Pfund',cu_sub_name_de='' WHERE cu_iso_3='GIP';
UPDATE static_currencies SET cu_name_de='Dalasi',cu_sub_name_de='' WHERE cu_iso_3='GMD';
UPDATE static_currencies SET cu_name_de='Guinea Franc',cu_sub_name_de='' WHERE cu_iso_3='GNF';
UPDATE static_currencies SET cu_name_de='Quetzal',cu_sub_name_de='' WHERE cu_iso_3='GTQ';
UPDATE static_currencies SET cu_name_de='Guinea Bissau Peso',cu_sub_name_de='' WHERE cu_iso_3='GWP';
UPDATE static_currencies SET cu_name_de='Guyana Dollar',cu_sub_name_de='' WHERE cu_iso_3='GYD';
UPDATE static_currencies SET cu_name_de='Hongkong Dollar',cu_sub_name_de='' WHERE cu_iso_3='HKD';
UPDATE static_currencies SET cu_name_de='Lempira',cu_sub_name_de='' WHERE cu_iso_3='HNL';
UPDATE static_currencies SET cu_name_de='Kuna',cu_sub_name_de='' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_de='Gourde',cu_sub_name_de='' WHERE cu_iso_3='HTG';
UPDATE static_currencies SET cu_name_de='Forint',cu_sub_name_de='' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_de='Rupiah',cu_sub_name_de='' WHERE cu_iso_3='IDR';
UPDATE static_currencies SET cu_name_de='Schekel',cu_sub_name_de='' WHERE cu_iso_3='ILS';
UPDATE static_currencies SET cu_name_de='Indische Rupie',cu_sub_name_de='' WHERE cu_iso_3='INR';
UPDATE static_currencies SET cu_name_de='Irak Dinar',cu_sub_name_de='' WHERE cu_iso_3='IQD';
UPDATE static_currencies SET cu_name_de='Rial',cu_sub_name_de='' WHERE cu_iso_3='IRR';
UPDATE static_currencies SET cu_name_de='Isländische Krone',cu_sub_name_de='' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_de='Jamaika Dollar',cu_sub_name_de='' WHERE cu_iso_3='JMD';
UPDATE static_currencies SET cu_name_de='Jordanischer Dinar',cu_sub_name_de='' WHERE cu_iso_3='JOD';
UPDATE static_currencies SET cu_name_de='Yen',cu_sub_name_de='' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_de='Kenia Schilling',cu_sub_name_de='' WHERE cu_iso_3='KES';
UPDATE static_currencies SET cu_name_de='Som',cu_sub_name_de='' WHERE cu_iso_3='KGS';
UPDATE static_currencies SET cu_name_de='Riel',cu_sub_name_de='' WHERE cu_iso_3='KHR';
UPDATE static_currencies SET cu_name_de='Komoren Franc',cu_sub_name_de='' WHERE cu_iso_3='KMF';
UPDATE static_currencies SET cu_name_de='Nordkoreanischer Won',cu_sub_name_de='' WHERE cu_iso_3='KPW';
UPDATE static_currencies SET cu_name_de='Südkoreanischer Won',cu_sub_name_de='' WHERE cu_iso_3='KRW';
UPDATE static_currencies SET cu_name_de='Kuwait Dinar',cu_sub_name_de='' WHERE cu_iso_3='KWD';
UPDATE static_currencies SET cu_name_de='Kaiman-Dollar',cu_sub_name_de='' WHERE cu_iso_3='KYD';
UPDATE static_currencies SET cu_name_de='Tenge',cu_sub_name_de='' WHERE cu_iso_3='KZT';
UPDATE static_currencies SET cu_name_de='Kip',cu_sub_name_de='' WHERE cu_iso_3='LAK';
UPDATE static_currencies SET cu_name_de='Libanesisches Pfund',cu_sub_name_de='' WHERE cu_iso_3='LBP';
UPDATE static_currencies SET cu_name_de='Sri Lanka Rupie',cu_sub_name_de='' WHERE cu_iso_3='LKR';
UPDATE static_currencies SET cu_name_de='Liberianischer Dollar',cu_sub_name_de='' WHERE cu_iso_3='LRD';
UPDATE static_currencies SET cu_name_de='Loti',cu_sub_name_de='' WHERE cu_iso_3='LSL';
UPDATE static_currencies SET cu_name_de='Litauischer Litas',cu_sub_name_de='' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_de='Lettischer Lats',cu_sub_name_de='' WHERE cu_iso_3='LVL';
UPDATE static_currencies SET cu_name_de='Libyscher Dinar',cu_sub_name_de='' WHERE cu_iso_3='LYD';
UPDATE static_currencies SET cu_name_de='Marokkanischer Dirham',cu_sub_name_de='' WHERE cu_iso_3='MAD';
UPDATE static_currencies SET cu_name_de='Moldau Leu',cu_sub_name_de='' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_de='Denar',cu_sub_name_de='' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_de='Kyat',cu_sub_name_de='' WHERE cu_iso_3='MMK';
UPDATE static_currencies SET cu_name_de='Tugrik',cu_sub_name_de='' WHERE cu_iso_3='MNT';
UPDATE static_currencies SET cu_name_de='Pataca',cu_sub_name_de='' WHERE cu_iso_3='MOP';
UPDATE static_currencies SET cu_name_de='Ouguiya',cu_sub_name_de='' WHERE cu_iso_3='MRO';
UPDATE static_currencies SET cu_name_de='Maltesische Lira',cu_sub_name_de='' WHERE cu_iso_3='MTL';
UPDATE static_currencies SET cu_name_de='Mauritius Rupie',cu_sub_name_de='' WHERE cu_iso_3='MUR';
UPDATE static_currencies SET cu_name_de='Rufiyaa',cu_sub_name_de='' WHERE cu_iso_3='MVR';
UPDATE static_currencies SET cu_name_de='Malawi Kwacha',cu_sub_name_de='' WHERE cu_iso_3='MWK';
UPDATE static_currencies SET cu_name_de='Mexikanischer Peso',cu_sub_name_de='' WHERE cu_iso_3='MXN';
UPDATE static_currencies SET cu_name_de='Malaysischer Ringgit',cu_sub_name_de='' WHERE cu_iso_3='MYR';
UPDATE static_currencies SET cu_name_de='Metical',cu_sub_name_de='' WHERE cu_iso_3='MZM';
UPDATE static_currencies SET cu_name_de='Namibia Dollar',cu_sub_name_de='' WHERE cu_iso_3='NAD';
UPDATE static_currencies SET cu_name_de='Naira',cu_sub_name_de='' WHERE cu_iso_3='NGN';
UPDATE static_currencies SET cu_name_de='Gold-Cordoba',cu_sub_name_de='' WHERE cu_iso_3='NIO';
UPDATE static_currencies SET cu_name_de='Norwegische Krone',cu_sub_name_de='' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_de='Nepalesische Rupie',cu_sub_name_de='' WHERE cu_iso_3='NPR';
UPDATE static_currencies SET cu_name_de='Neuseeland Dollar',cu_sub_name_de='' WHERE cu_iso_3='NZD';
UPDATE static_currencies SET cu_name_de='Rial Omani',cu_sub_name_de='' WHERE cu_iso_3='OMR';
UPDATE static_currencies SET cu_name_de='Balboa',cu_sub_name_de='' WHERE cu_iso_3='PAB';
UPDATE static_currencies SET cu_name_de='Neuer Sol',cu_sub_name_de='' WHERE cu_iso_3='PEN';
UPDATE static_currencies SET cu_name_de='Kina',cu_sub_name_de='' WHERE cu_iso_3='PGK';
UPDATE static_currencies SET cu_name_de='Philippinischer Peso',cu_sub_name_de='' WHERE cu_iso_3='PHP';
UPDATE static_currencies SET cu_name_de='Pakistanische Rupie',cu_sub_name_de='' WHERE cu_iso_3='PKR';
UPDATE static_currencies SET cu_name_de='Zloty',cu_sub_name_de='' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_de='Guarani',cu_sub_name_de='' WHERE cu_iso_3='PYG';
UPDATE static_currencies SET cu_name_de='Katar Riyal',cu_sub_name_de='' WHERE cu_iso_3='QAR';
UPDATE static_currencies SET cu_name_de='Leu',cu_sub_name_de='' WHERE cu_iso_3='ROL';
UPDATE static_currencies SET cu_name_de='Russischer Rubel (neu)',cu_sub_name_de='' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_de='Ruanda Franc',cu_sub_name_de='' WHERE cu_iso_3='RWF';
UPDATE static_currencies SET cu_name_de='Saudi Riyal',cu_sub_name_de='' WHERE cu_iso_3='SAR';
UPDATE static_currencies SET cu_name_de='Salomonen Dollar',cu_sub_name_de='' WHERE cu_iso_3='SBD';
UPDATE static_currencies SET cu_name_de='Seychellen Rupie',cu_sub_name_de='' WHERE cu_iso_3='SCR';
UPDATE static_currencies SET cu_name_de='Sudanesischer Dinar',cu_sub_name_de='' WHERE cu_iso_3='SDD';
UPDATE static_currencies SET cu_name_de='Schwedische Krone',cu_sub_name_de='' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_de='Singapur Dollar',cu_sub_name_de='' WHERE cu_iso_3='SGD';
UPDATE static_currencies SET cu_name_de='St. Helena Pfund',cu_sub_name_de='' WHERE cu_iso_3='SHP';
UPDATE static_currencies SET cu_name_de='Tolar',cu_sub_name_de='' WHERE cu_iso_3='SIT';
UPDATE static_currencies SET cu_name_de='Slowakische Krone',cu_sub_name_de='' WHERE cu_iso_3='SKK';
UPDATE static_currencies SET cu_name_de='Leone',cu_sub_name_de='' WHERE cu_iso_3='SLL';
UPDATE static_currencies SET cu_name_de='Somalia Schilling',cu_sub_name_de='' WHERE cu_iso_3='SOS';
UPDATE static_currencies SET cu_name_de='Dobra',cu_sub_name_de='' WHERE cu_iso_3='STD';
UPDATE static_currencies SET cu_name_de='El Salvador Colon',cu_sub_name_de='' WHERE cu_iso_3='SVC';
UPDATE static_currencies SET cu_name_de='Syrisches Pfund',cu_sub_name_de='' WHERE cu_iso_3='SYP';
UPDATE static_currencies SET cu_name_de='Lilangeni',cu_sub_name_de='' WHERE cu_iso_3='SZL';
UPDATE static_currencies SET cu_name_de='Baht',cu_sub_name_de='' WHERE cu_iso_3='THB';
UPDATE static_currencies SET cu_name_de='Tadschikistan Somoni',cu_sub_name_de='' WHERE cu_iso_3='TJS';
UPDATE static_currencies SET cu_name_de='Turkmenistan-Manat',cu_sub_name_de='' WHERE cu_iso_3='TMM';
UPDATE static_currencies SET cu_name_de='Tunesischer Dinar',cu_sub_name_de='' WHERE cu_iso_3='TND';
UPDATE static_currencies SET cu_name_de='Paʻanga',cu_sub_name_de='' WHERE cu_iso_3='TOP';
UPDATE static_currencies SET cu_name_de='Trinidad und Tobago Dollar',cu_sub_name_de='' WHERE cu_iso_3='TTD';
UPDATE static_currencies SET cu_name_de='Neuer Taiwan Dollar',cu_sub_name_de='' WHERE cu_iso_3='TWD';
UPDATE static_currencies SET cu_name_de='Tansania Schilling',cu_sub_name_de='' WHERE cu_iso_3='TZS';
UPDATE static_currencies SET cu_name_de='Hryvnia',cu_sub_name_de='' WHERE cu_iso_3='UAH';
UPDATE static_currencies SET cu_name_de='Uganda Schilling',cu_sub_name_de='' WHERE cu_iso_3='UGX';
UPDATE static_currencies SET cu_name_de='US Dollar',cu_sub_name_de='' WHERE cu_iso_3='USD';
UPDATE static_currencies SET cu_name_de='Uruguayischer Peso',cu_sub_name_de='' WHERE cu_iso_3='UYU';
UPDATE static_currencies SET cu_name_de='Usbekistan Sum',cu_sub_name_de='' WHERE cu_iso_3='UZS';
UPDATE static_currencies SET cu_name_de='Bolivar',cu_sub_name_de='' WHERE cu_iso_3='VEB';
UPDATE static_currencies SET cu_name_de='Dong',cu_sub_name_de='' WHERE cu_iso_3='VND';
UPDATE static_currencies SET cu_name_de='Vatu',cu_sub_name_de='' WHERE cu_iso_3='VUV';
UPDATE static_currencies SET cu_name_de='Tala',cu_sub_name_de='' WHERE cu_iso_3='WST';
UPDATE static_currencies SET cu_name_de='CFA Franc (Äquatorial)',cu_sub_name_de='' WHERE cu_iso_3='XAF';
UPDATE static_currencies SET cu_name_de='Ostkaribischer Dollar',cu_sub_name_de='' WHERE cu_iso_3='XCD';
UPDATE static_currencies SET cu_name_de='CFA Franc (West)',cu_sub_name_de='' WHERE cu_iso_3='XOF';
UPDATE static_currencies SET cu_name_de='CFP Franc',cu_sub_name_de='' WHERE cu_iso_3='XPF';
UPDATE static_currencies SET cu_name_de='Jemen Rial',cu_sub_name_de='' WHERE cu_iso_3='YER';
UPDATE static_currencies SET cu_name_de='Rand',cu_sub_name_de='' WHERE cu_iso_3='ZAR';
UPDATE static_currencies SET cu_name_de='Kwacha',cu_sub_name_de='' WHERE cu_iso_3='ZMK';
UPDATE static_currencies SET cu_name_de='Simbabwe Dollar',cu_sub_name_de='' WHERE cu_iso_3='ZWD';
UPDATE static_currencies SET cu_name_de='Afghani',cu_sub_name_de='' WHERE cu_iso_3='AFN';
UPDATE static_currencies SET cu_name_de='',cu_sub_name_de='' WHERE cu_iso_3='CSD';
UPDATE static_currencies SET cu_name_de='Madagaskar Ariary',cu_sub_name_de='' WHERE cu_iso_3='MGA';
UPDATE static_currencies SET cu_name_de='',cu_sub_name_de='' WHERE cu_iso_3='SRD';
UPDATE static_currencies SET cu_name_de='Neue Türkische Lira',cu_sub_name_de='' WHERE cu_iso_3='TRY';


## static_languages
UPDATE static_languages SET lg_name_de='Abchasisch' WHERE lg_iso_2='AB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Afar' WHERE lg_iso_2='AA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Afrikaans' WHERE lg_iso_2='AF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Albanisch' WHERE lg_iso_2='SQ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Amharisch' WHERE lg_iso_2='AM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Arabisch' WHERE lg_iso_2='AR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Armenisch' WHERE lg_iso_2='HY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Assamesisch' WHERE lg_iso_2='AS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Aymará-Sprache' WHERE lg_iso_2='AY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Aserbaidschanisch' WHERE lg_iso_2='AZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Baschkirisch' WHERE lg_iso_2='BA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Baskisch' WHERE lg_iso_2='EU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Bengalisch' WHERE lg_iso_2='BN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Bhutanisch' WHERE lg_iso_2='DZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Biharisch' WHERE lg_iso_2='BH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Bislama' WHERE lg_iso_2='BI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Bretonisch' WHERE lg_iso_2='BR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Bulgarisch' WHERE lg_iso_2='BG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Birmanisch' WHERE lg_iso_2='MY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Weißrussisch' WHERE lg_iso_2='BE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kambodschanisch' WHERE lg_iso_2='KM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Katalanisch' WHERE lg_iso_2='CA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Zhuang' WHERE lg_iso_2='ZA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Chinesisch' WHERE lg_iso_2='ZH' AND lg_country_iso_2='HK';
UPDATE static_languages SET lg_name_de='Korsisch' WHERE lg_iso_2='CO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kroatisch' WHERE lg_iso_2='HR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Tschechisch' WHERE lg_iso_2='CS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Dänisch' WHERE lg_iso_2='DA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Niederländisch' WHERE lg_iso_2='NL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Englisch' WHERE lg_iso_2='EN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Esperanto' WHERE lg_iso_2='EO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Estnisch' WHERE lg_iso_2='ET' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Färöisch' WHERE lg_iso_2='FO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Persisch' WHERE lg_iso_2='FA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Fidschianisch' WHERE lg_iso_2='FJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Finnisch' WHERE lg_iso_2='FI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Französisch' WHERE lg_iso_2='FR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Friesisch' WHERE lg_iso_2='FY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Galizisch' WHERE lg_iso_2='GL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Schottisch-Gälisch' WHERE lg_iso_2='GD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Manx' WHERE lg_iso_2='GV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Georgisch' WHERE lg_iso_2='KA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Deutsch' WHERE lg_iso_2='DE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Griechisch' WHERE lg_iso_2='EL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Grönländisch' WHERE lg_iso_2='KL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Guarani' WHERE lg_iso_2='GN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Gujarati' WHERE lg_iso_2='GU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Hausa' WHERE lg_iso_2='HA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Hebräisch' WHERE lg_iso_2='HE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Hindi' WHERE lg_iso_2='HI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Ungarisch' WHERE lg_iso_2='HU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Isländisch' WHERE lg_iso_2='IS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Indonesisch' WHERE lg_iso_2='ID' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Inukitut' WHERE lg_iso_2='IU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Inupiak' WHERE lg_iso_2='IK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Irisch' WHERE lg_iso_2='GA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Italienisch' WHERE lg_iso_2='IT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Japanisch' WHERE lg_iso_2='JA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kannada' WHERE lg_iso_2='KN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kaschmirisch' WHERE lg_iso_2='KS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kasachisch' WHERE lg_iso_2='KK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Ruandisch' WHERE lg_iso_2='RW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kirgisisch' WHERE lg_iso_2='KY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Rundi-Sprache' WHERE lg_iso_2='RN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Koreanisch' WHERE lg_iso_2='KO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kurdisch' WHERE lg_iso_2='KU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Laotisch' WHERE lg_iso_2='LO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Lettisch' WHERE lg_iso_2='LV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Lingala' WHERE lg_iso_2='LN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Litauisch' WHERE lg_iso_2='LT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Mazedonisch' WHERE lg_iso_2='MK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Madagassisch' WHERE lg_iso_2='MG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Malaiisch' WHERE lg_iso_2='MS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Malayalam' WHERE lg_iso_2='ML' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Maltesisch' WHERE lg_iso_2='MT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Maori' WHERE lg_iso_2='MI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Marathi' WHERE lg_iso_2='MR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Moldauisch' WHERE lg_iso_2='MO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Mongolisch' WHERE lg_iso_2='MN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Nauruisch' WHERE lg_iso_2='NA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Nepalesisch' WHERE lg_iso_2='NE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Norwegisch' WHERE lg_iso_2='NO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Okzitanisch' WHERE lg_iso_2='OC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Orija' WHERE lg_iso_2='OR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Oromo' WHERE lg_iso_2='OM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Afghanisch (Paschtu)' WHERE lg_iso_2='PS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Polnisch' WHERE lg_iso_2='PL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Portugiesisch' WHERE lg_iso_2='PT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Pandschabisch' WHERE lg_iso_2='PA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Quechua' WHERE lg_iso_2='QU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Rätoromanisch' WHERE lg_iso_2='RM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Rumänisch' WHERE lg_iso_2='RO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Russisch' WHERE lg_iso_2='RU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Samoanisch' WHERE lg_iso_2='SM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Sango' WHERE lg_iso_2='SG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Serbisch' WHERE lg_iso_2='SR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Süd-Sotho-Sprache' WHERE lg_iso_2='ST' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Tswana-Sprache' WHERE lg_iso_2='TN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Shona' WHERE lg_iso_2='SN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Sindhi' WHERE lg_iso_2='SD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Singhalesisch' WHERE lg_iso_2='SI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Swazi' WHERE lg_iso_2='SS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Slowakisch' WHERE lg_iso_2='SK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Slowenisch' WHERE lg_iso_2='SL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Somali' WHERE lg_iso_2='SO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Spanisch' WHERE lg_iso_2='ES' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Sudanesisch' WHERE lg_iso_2='SU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Suaheli' WHERE lg_iso_2='SW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Schwedisch' WHERE lg_iso_2='SV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Tagalog' WHERE lg_iso_2='TL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Tadschikisch' WHERE lg_iso_2='TG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Tamilisch' WHERE lg_iso_2='TA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Tatarisch' WHERE lg_iso_2='TT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Telugu' WHERE lg_iso_2='TE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Thai' WHERE lg_iso_2='TH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Tibetisch' WHERE lg_iso_2='BO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Tigrinja' WHERE lg_iso_2='TI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Tongaisch' WHERE lg_iso_2='TO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Tsonga' WHERE lg_iso_2='TS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Türkisch' WHERE lg_iso_2='TR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Turkmenisch' WHERE lg_iso_2='TK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Twi' WHERE lg_iso_2='TW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Uigurisch' WHERE lg_iso_2='UG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Ukrainisch' WHERE lg_iso_2='UK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Urdu' WHERE lg_iso_2='UR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Usbekisch' WHERE lg_iso_2='UZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Vietnamesisch' WHERE lg_iso_2='VI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kymrisch' WHERE lg_iso_2='CY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Wolof' WHERE lg_iso_2='WO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Xhosa' WHERE lg_iso_2='XH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Joruba' WHERE lg_iso_2='YO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Zulu' WHERE lg_iso_2='ZU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Bosnisch' WHERE lg_iso_2='BS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Akan' WHERE lg_iso_2='AK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Aragonesisch' WHERE lg_iso_2='AN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Awarisch' WHERE lg_iso_2='AV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Bambara-Sprache' WHERE lg_iso_2='BM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Tschetschenisch' WHERE lg_iso_2='CE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Chamorro-Sprache' WHERE lg_iso_2='CH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Cree' WHERE lg_iso_2='CR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Tschuwaschisch' WHERE lg_iso_2='CV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Maledivisch' WHERE lg_iso_2='DV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Ewe-Sprache' WHERE lg_iso_2='EE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Ful' WHERE lg_iso_2='FF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Hiri-Motu' WHERE lg_iso_2='HO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kreolisch' WHERE lg_iso_2='HT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Herero-Sprache' WHERE lg_iso_2='HZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Igbo-Sprache' WHERE lg_iso_2='IG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Sichuan Yi' WHERE lg_iso_2='II' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kongo' WHERE lg_iso_2='KG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kikuyu-Sprache' WHERE lg_iso_2='KI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kwanyama' WHERE lg_iso_2='KJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kanuri-Sprache' WHERE lg_iso_2='KR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Komi-Sprache' WHERE lg_iso_2='KV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kornisch' WHERE lg_iso_2='KW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Luxemburgisch' WHERE lg_iso_2='LB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Ganda-Sprache' WHERE lg_iso_2='LG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Limburgisch' WHERE lg_iso_2='LI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Luba' WHERE lg_iso_2='LU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Marschallesisch' WHERE lg_iso_2='MH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Norwegisch Bokmål' WHERE lg_iso_2='NB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Ndebele-Sprache (Nord)' WHERE lg_iso_2='ND' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Ndonga' WHERE lg_iso_2='NG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Norwegisch Nynorsk' WHERE lg_iso_2='NN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Ndebele-Sprache (Süd)' WHERE lg_iso_2='NR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Navajo-Sprache' WHERE lg_iso_2='NV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Chewa-Sprache' WHERE lg_iso_2='NY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Ojibwa-Sprache' WHERE lg_iso_2='OJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Ossetisch' WHERE lg_iso_2='OS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Sardisch' WHERE lg_iso_2='SC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Nord-Samisch' WHERE lg_iso_2='SE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Tahitisch' WHERE lg_iso_2='TY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Venda-Sprache' WHERE lg_iso_2='VE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Wallonisch' WHERE lg_iso_2='WA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Javanisch' WHERE lg_iso_2='JV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Portugiesisch' WHERE lg_iso_2='PT' AND lg_country_iso_2='BR';
UPDATE static_languages SET lg_name_de='Chinesisch' WHERE lg_iso_2='ZH' AND lg_country_iso_2='CN';
UPDATE static_languages SET lg_name_de='Interlingua' WHERE lg_iso_2='IA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Interlingue' WHERE lg_iso_2='IE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Latein' WHERE lg_iso_2='LA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Sanskrit' WHERE lg_iso_2='SA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Volapük' WHERE lg_iso_2='VO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Jiddisch' WHERE lg_iso_2='YI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Avestisch' WHERE lg_iso_2='AE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Kirchenslawisch' WHERE lg_iso_2='CU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Ido-Sprache' WHERE lg_iso_2='IO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_de='Pali' WHERE lg_iso_2='PI' AND lg_country_iso_2='';

