<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2013-02-27 09:31

$extensionClassesPath = t3lib_extMgm::extPath( 't3_less' ) . 'Classes/';
return array(
	'tx_t3less_controller_basecontroller' => $extensionClassesPath . 'Controller/BaseController.php',
	'tx_t3less_controller_lessphpcontroller' => $extensionClassesPath . 'Controller/LessPhpController.php',
	'tx_t3less_controller_lessjscontroller' => $extensionClassesPath . 'Controller/LessJsController.php',
	'tx_t3less_controller_lessjsnodecontroller' => $extensionClassesPath . 'Controller/LessJsNodeController.php',
	'tx_t3less_utility_utilities' => $extensionClassesPath . 'Utility/Utilities.php',
);
?>